# Generated by Django 3.1.5 on 2021-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='Name',
        ),
        migrations.AddField(
            model_name='square',
            name='Column',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='square',
            name='Row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='square',
            name='Terrain',
            field=models.TextField(default='Grass'),
        ),
    ]
