# Generated by Django 3.1.5 on 2021-08-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='Colums',
        ),
        migrations.AddField(
            model_name='main',
            name='Columns',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='main',
            name='Rows',
            field=models.IntegerField(default=3),
        ),
    ]
