# Generated by Django 3.1.5 on 2021-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_main_testnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='Discovered',
            field=models.BooleanField(default=False),
        ),
    ]
