# Generated by Django 3.1.5 on 2021-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_main_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Year',
            field=models.IntegerField(default=0),
        ),
    ]
