# Generated by Django 3.1.5 on 2021-08-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_main_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Price_discover_tile',
            field=models.IntegerField(default=20),
        ),
    ]
