# Generated by Django 3.1.5 on 2021-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_auto_20210910_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='NumberOfGrassTiles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='main',
            name='NumberOfWaterTiles',
            field=models.IntegerField(default=0),
        ),
    ]
