# Generated by Django 3.1.5 on 2021-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0013_auto_20210910_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='FoodForGrass',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='main',
            name='FoodForWater',
            field=models.IntegerField(default=0),
        ),
    ]
