# Generated by Django 3.1.5 on 2021-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0014_auto_20210910_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='TextEvent',
            field=models.TextField(default='Default text'),
        ),
    ]
