# Generated by Django 3.1.5 on 2021-09-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0017_auto_20210919_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='TextEndEvent',
            field=models.TextField(default='Default EndText'),
        ),
    ]
