# Generated by Django 3.1.5 on 2021-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0020_main_boat'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='GameEnded',
            field=models.BooleanField(default=False),
        ),
    ]
