# Generated by Django 3.1.5 on 2021-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0021_main_gameended'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='GameEndedSucces',
            field=models.BooleanField(default=False),
        ),
    ]
