# Generated by Django 3.1.5 on 2021-10-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0024_main_gameendedhighscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Berry',
            field=models.BooleanField(default=False),
        ),
    ]
