# Generated by Django 3.1.5 on 2021-10-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0025_main_berry'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Sacrifice',
            field=models.BooleanField(default=False),
        ),
    ]
