# Generated by Django 3.1.5 on 2021-12-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0026_main_sacrifice'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='Save',
            field=models.BooleanField(default=False),
        ),
    ]
