# Generated by Django 3.1.5 on 2021-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0027_square_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='PriceBuildFarm',
            field=models.IntegerField(default=50),
        ),
    ]
