# Generated by Django 3.1.5 on 2021-12-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0028_main_pricebuildfarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='FoodForFarm',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='main',
            name='FoodForFarmCurrentYear',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='main',
            name='NumberOfFarmTiles',
            field=models.IntegerField(default=0),
        ),
    ]
