# Generated by Django 3.1.5 on 2021-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0029_auto_20211219_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Phase',
            field=models.IntegerField(default=1),
        ),
    ]
