# Generated by Django 3.1.5 on 2021-12-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0030_main_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='GameEndedHighscore',
        ),
        migrations.RemoveField(
            model_name='main',
            name='GameEndedSucces',
        ),
    ]
