# Generated by Django 3.1.5 on 2021-12-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0031_auto_20211219_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='SubmitHighscore',
            field=models.BooleanField(default=False),
        ),
    ]
