# Generated by Django 3.1.5 on 2021-12-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0032_main_submithighscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Population',
            field=models.IntegerField(default=100),
        ),
    ]
