# Generated by Django 3.1.5 on 2021-12-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0033_main_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='PopulationLastYear',
            field=models.IntegerField(default=100),
        ),
    ]
