# Generated by Django 3.1.5 on 2021-12-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0034_main_populationlastyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='PopulationChange',
            field=models.IntegerField(default=0),
        ),
    ]
