# Generated by Django 3.1.5 on 2021-12-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0035_main_populationchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Farmers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='Idle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='Soldiers',
            field=models.IntegerField(default=0),
        ),
    ]
