# Generated by Django 3.1.5 on 2021-12-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0037_main_nextyearblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='OccupationsAreSet',
            field=models.BooleanField(default=False),
        ),
    ]
