# Generated by Django 3.1.5 on 2021-12-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0038_main_occupationsareset'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='FarmEffectiveness',
            field=models.IntegerField(default=0),
        ),
    ]
