# Generated by Django 3.1.5 on 2021-12-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0039_main_farmeffectiveness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='FoodForFarm',
            field=models.IntegerField(default=50),
        ),
    ]
