# Generated by Django 3.1.5 on 2021-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0040_auto_20211231_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='FarmFoodGained',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='main',
            name='FoodForFarmCurrentYear',
            field=models.IntegerField(default=50),
        ),
    ]
