# Generated by Django 3.1.5 on 2022-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0042_main_foodgained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='Testnumber',
        ),
        migrations.AddField(
            model_name='main',
            name='War',
            field=models.BooleanField(default=False),
        ),
    ]
