# Generated by Django 3.1.5 on 2022-01-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0043_auto_20220104_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='FoodLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='PopulationKilled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='TilesUndiscovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='WarWon',
            field=models.BooleanField(default=False),
        ),
    ]
