# Generated by Django 3.1.5 on 2022-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0044_auto_20220104_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='WarWon',
        ),
        migrations.AddField(
            model_name='main',
            name='WarOutcome',
            field=models.TextField(default='Win'),
        ),
    ]
