# Generated by Django 3.1.5 on 2022-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0046_auto_20220107_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='WarOpponentSoldiers',
            field=models.IntegerField(default=0),
        ),
    ]
