# Generated by Django 3.1.5 on 2022-01-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0047_main_waropponentsoldiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='EventList',
            field=models.TextField(default='1-2-3-4-5-6-7-8-9-10'),
        ),
    ]
