# Generated by Django 3.1.5 on 2022-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0048_main_eventlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='CurrentEvent',
            field=models.TextField(default='0'),
        ),
    ]
