# Generated by Django 3.1.5 on 2022-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0049_main_currentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Writing',
            field=models.TextField(default=''),
        ),
    ]
