# Generated by Django 3.1.5 on 2022-01-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0050_main_writing'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='FarmEffectivenessBonus',
            field=models.IntegerField(default=0),
        ),
    ]
