# Generated by Django 3.1.5 on 2022-01-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0051_main_farmeffectivenessbonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='FarmEffectivenessBonus',
        ),
    ]
