# Generated by Django 3.1.5 on 2022-01-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0052_remove_main_farmeffectivenessbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='SoldiersEffectiveness',
            field=models.IntegerField(default=100),
        ),
    ]
