# Generated by Django 3.1.5 on 2022-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0053_main_soldierseffectiveness'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='SoldiersEffectivenessCurrentYear',
            field=models.IntegerField(default=100),
        ),
    ]
