# Generated by Django 3.1.5 on 2022-01-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0054_main_soldierseffectivenesscurrentyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Pyramid',
            field=models.BooleanField(default=False),
        ),
    ]
