# Generated by Django 3.1.5 on 2022-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0055_main_pyramid'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Trojan',
            field=models.BooleanField(default=False),
        ),
    ]
