# Generated by Django 3.1.5 on 2022-01-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0056_main_trojan'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Codex',
            field=models.BooleanField(default=False),
        ),
    ]
