# Generated by Django 3.1.5 on 2022-01-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0057_main_codex'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Smith',
            field=models.TextField(default=''),
        ),
    ]
