# Generated by Django 3.1.5 on 2022-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0058_main_smith'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Leadership',
            field=models.TextField(default=''),
        ),
    ]
