# Generated by Django 3.1.5 on 2022-01-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0059_main_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Christianity',
            field=models.BooleanField(default=False),
        ),
    ]
