# Generated by Django 3.1.5 on 2022-01-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0060_main_christianity'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Wall',
            field=models.BooleanField(default=False),
        ),
    ]
