# Generated by Django 3.1.5 on 2022-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0061_main_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='Phase',
            field=models.TextField(default='Phase 1'),
        ),
    ]
