# Generated by Django 3.1.5 on 2022-01-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0062_highscore_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highscore',
            old_name='Food',
            new_name='Score',
        ),
    ]
