# Generated by Django 3.1.5 on 2022-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0063_auto_20220124_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='TestMode',
            field=models.BooleanField(default=False),
        ),
    ]
